name: trackers
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sidebarx: ^0.17.1
  get: ^4.6.6
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  email_validator: ^2.0.1
  url_launcher: ^6.0.20
  logger: ^2.5.0
  qr_flutter: ^4.1.0
  timer_count_down: ^2.2.2
  flutter_countdown_timer: ^4.1.0
  http: any
  fluttertoast: ^8.0.8
  mysql1: ^0.20.0
  provider: ^6.1.2
  http_client: ^1.5.3
  http_profile: ^0.1.0
  database_query_builder: ^0.0.7
  php_serializer: ^1.2.0
  shared_preferences: ^2.3.3

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/trainBackgrong/
    
